platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'


target "WorldviewTribute" do
    pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :tag => 'v2.4.1_beta7'
end
